### ISSUE TITLE
Debug mode error

### ISSUE THREAD

**Issue by kunzi** [facebookincubator/facebook-for-magento#85]
I'm trying to enter the debug mode, but I get this error:
```
Warning: include_once(Facebook_AdsExtension_Model_FBProductFeedSamples.php): failed to open stream: No such file or directory  in /public_html/app/code/community/Facebook/AdsExtension/controllers/Adminhtml/FbdebugController.php on line 20

#0 /public_html/app/code/community/Facebook/AdsExtension/controllers/Adminhtml/FbdebugController.php(20): mageCoreErrorHandler(2, 'include_once(Fa...', '', 20, Array)
#1 /public_html/app/code/community/Facebook/AdsExtension/controllers/Adminhtml/FbdebugController.php(20): include_once()
#2 /public_html/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(337): include('')
#3 /public_html/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(308): Mage_Core_Controller_Varien_Router_Standard->_includeControllerClass('', 'Facebook_AdsExt...')
#4 /public_html/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(196): Mage_Core_Controller_Varien_Router_Standard->_validateControllerClassName('Facebook_AdsExt...', 'fbdebug')
#5 /public_html/app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#6 /public_html/app/code/core/Mage/Core/Model/App.php(365): Mage_Core_Controller_Varien_Front->dispatch()
#7 /public_html/app/Mage.php(683): Mage_Core_Model_App->run(Array)
#8 /public_html/index.php(89): Mage::run('', 'store')
```

I installed the extension via Magento Connect.

**Comment by kunzi** [comment]
I fixed this issue by editing lines 17 and 18 in /app/code/community/Facebook/AdsExtension/controllers/Adminhtml/FbdebugController.php to be like this:

if (file_exists(__DIR__.'/../../Model/FBProductFeedSamples.php')) {
  include_once __DIR__.'/../../Model/FBProductFeedSamples.php';

**Comment by dmitridr** [comment]
Hi @kunzi good find! Would you mind sending us a PR to fix that? Would love to give you credit for that.

**Comment by dmitridr** [comment]
Just a heads up though, If you don't send it in 1-2 days we will probably add the fix ourselves, seems pretty important!
